apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tier: db
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
      # nodePort: {{ .Values.postgresql.service.nodePort }}
  selector:
    app: {{ .Chart.Name }}
    tier: db