services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: betting-frontend
    # ports:
    #   - "80:3000"
    # environment:
    #   API_ADDR: backend
    #   API_PORT: 8080
    # depends_on:
    #   backend:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://frontend:3000/api/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "80:8080"
    container_name: betting-backend
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/api/v1/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    # environment:
    #   BACKEND_DB_URL: postgres://postgres:postgres@postgres:5432/betting
    #   BACKEND_DB_NAME: betting
    #   BACKEND_DB_USER: postgres
    #   BACKEND_DB_PASSWORD: postgres
    #   BACKEND_DB_HOST: postgres
    #   BACKEND_DB_PORT: 5432
    #   REDIS_HOST: redis
    #   REDIS_PORT: 6379
    #   JWT_SECRET: your-secret-key-change-me
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:16
    container_name: betting-postgres
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=betting

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: betting-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network    
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z zookeeper 2181"]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: betting-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    networks:
      - app-network    
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z kafka 9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.0-rc1
    container_name: betting-redis
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass myredispass
    restart: always
    networks:
      - app-network    
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge