import type { Metadata } from "next";
import "@/styles/globals.css";
import Layout from "@/components/Layout";
import DeviceTracker from "@/components/Common/DeviceTracker"; 

export const metadata: Metadata = {
  title: "Betting",
  description: "Generated by Betting",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      <DeviceTracker />
      {children}
    </Layout>
  );
}
