"use client";

import React from "react";

import EventSidebar from "@/components/Home/EventSidebar";
import ProfileCard from "@/components/Profile/ProfileCard";

// import type { Metadata } from "next";
import { Splitter } from "antd";
import Layout from "@/components/Layout";
import "@/styles/globals.css";
import DeviceTracker from "@/components/Common/DeviceTracker";
import ContactCard from "@/components/Common/Contact";
/* 
export const metadata: Metadata = {
  title: "Betting",
  description: "Generated by Betting",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      <DeviceTracker />
      <Splitter className="shadow">
        <Splitter.Panel
          defaultSize="20%"
          max="40%"
          style={{
            scrollbarWidth: "inherit",
          }}
          className="!pr-2 h-[calc(100vh-40px)] hidden md:block"
          collapsible
        >
          <EventSidebar />
        </Splitter.Panel>
        <Splitter.Panel
          defaultSize="80%"
          style={{
            scrollbarWidth: "inherit",
          }}
          className="!basis-full"
        >
          <div className="flex">
            <div className="w-full md:w-3/4">{children}</div>
            <div
              style={{
                scrollbarWidth: "inherit",
              }}
              // defaultSize="20%"
              // max="40%"
              className="w-1/4 h-[calc(100vh-40px)] hidden md:block"
              // collapsible
            >
              <ProfileCard />

              <ContactCard />
            </div>
          </div>
        </Splitter.Panel>
      </Splitter>
    </Layout>
  );
}
