"use client";

import React from "react";

import EventSidebar from "@/components/Home/EventSidebar";
import ProfileCard from "@/components/Profile/ProfileCard";

// import type { Metadata } from "next";
import { Splitter } from "antd";
import Layout from "@/components/Layout";
import "@/styles/globals.css";
import DeviceTracker from "@/components/Common/DeviceTracker";
import ContactCard from "@/components/Common/Contact";
/* 
export const metadata: Metadata = {
  title: "Betting",
  description: "Generated by Betting",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      <DeviceTracker />
      <Splitter className="shadow">
        <Splitter.Panel
          defaultSize="20%"
          min="20%"
          max="40%"
          style={{
            scrollbarWidth: "inherit",
          }}
          className="!pr-2 h-[calc(100vh-40px)]"
          collapsible
        >
          <EventSidebar />
        </Splitter.Panel>
        <Splitter.Panel
          defaultSize="60%"
          style={{
            scrollbarWidth: "inherit",
          }}
        >
          {children}
        </Splitter.Panel>
        <Splitter.Panel
          style={{
            scrollbarWidth: "inherit",
          }}
          defaultSize="20%"
          min="20%"
          max="40%"
          className="h-[calc(100vh-40px)]"
          collapsible={true}
        >
          <ProfileCard />

          <ContactCard />
        </Splitter.Panel>
      </Splitter>
    </Layout>
  );
}
