package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"time"

	"github.com/hotbrainy/go-betting/backend/graph/generated"
	"github.com/hotbrainy/go-betting/backend/graph/model"
	"github.com/hotbrainy/go-betting/backend/internal/loaders"
	"github.com/hotbrainy/go-betting/backend/internal/models"
)

// ShowFrom is the resolver for the showFrom field.
func (r *announcementResolver) ShowFrom(ctx context.Context, obj *models.Announcement) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: ShowFrom - showFrom"))
}

// ShowTo is the resolver for the showTo field.
func (r *announcementResolver) ShowTo(ctx context.Context, obj *models.Announcement) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: ShowTo - showTo"))
}

// CreateAnnouncement is the resolver for the createAnnouncement field.
func (r *mutationResolver) CreateAnnouncement(ctx context.Context, input model.NewAnnouncementInput) (*models.Announcement, error) {
	ldr := loaders.For(ctx)
	return ldr.AnnouncementReader.CreateAnnouncement(ctx, input)
}

// UpdateAnnouncement is the resolver for the updateAnnouncement field.
func (r *mutationResolver) UpdateAnnouncement(ctx context.Context, id uint, input model.UpdateAnnouncementInput) (*models.Announcement, error) {
	ldr := loaders.For(ctx)
	return ldr.AnnouncementReader.UpdateAnnouncement(ctx, id, input)
}

// DeleteAnnouncement is the resolver for the deleteAnnouncement field.
func (r *mutationResolver) DeleteAnnouncement(ctx context.Context, id uint) (bool, error) {
	ldr := loaders.For(ctx)
	return ldr.AnnouncementReader.DeleteAnnouncement(ctx, id)
}

// Announcements is the resolver for the announcements field.
func (r *queryResolver) Announcements(ctx context.Context) ([]*models.Announcement, error) {
	ldr := loaders.For(ctx)
	return ldr.AnnouncementReader.GetLatestAnnouncements(ctx)
}

// GetAnnouncements is the resolver for the getAnnouncements field.
func (r *queryResolver) GetAnnouncements(ctx context.Context, filters []*model.Filter, orders []*model.Order, pagination *model.Pagination) (*model.AnnouncementList, error) {
	ldr := loaders.For(ctx)
	return ldr.AnnouncementReader.GetAnnouncements(ctx, filters, orders, pagination)
}

// Announcement returns generated.AnnouncementResolver implementation.
func (r *Resolver) Announcement() generated.AnnouncementResolver { return &announcementResolver{r} }

type announcementResolver struct{ *Resolver }
