package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"

	"github.com/hotbrainy/go-betting/backend/graph/model"
	"github.com/hotbrainy/go-betting/backend/internal/loaders"
	"github.com/hotbrainy/go-betting/backend/internal/models"
)

// CreateAnnouncement is the resolver for the createAnnouncement field.
func (r *mutationResolver) CreateAnnouncement(ctx context.Context, input model.NewAnnouncementInput) (*models.Announcement, error) {
	ldr := loaders.For(ctx)
	return ldr.AnnouncementReader.CreateAnnouncement(ctx, input)
}

// UpdateAnnouncement is the resolver for the updateAnnouncement field.
func (r *mutationResolver) UpdateAnnouncement(ctx context.Context, id uint, input model.UpdateAnnouncementInput) (*models.Announcement, error) {
	ldr := loaders.For(ctx)
	return ldr.AnnouncementReader.UpdateAnnouncement(ctx, id, input)
}

// DeleteAnnouncement is the resolver for the deleteAnnouncement field.
func (r *mutationResolver) DeleteAnnouncement(ctx context.Context, id uint) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAnnouncement - deleteAnnouncement"))
}

// GetAnnouncements is the resolver for the getAnnouncements field.
func (r *queryResolver) GetAnnouncements(ctx context.Context, filters []*model.Filter, orders []*model.Order, pagination *model.Pagination) (*model.AnnouncementList, error) {
	ldr := loaders.For(ctx)
	return ldr.AnnouncementReader.GetAnnouncements(ctx, filters, orders, pagination)
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *announcementResolver) Type(ctx context.Context, obj *models.Announcement) (string, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}
func (r *announcementResolver) DomainID(ctx context.Context, obj *models.Announcement) (*uint, error) {
	panic(fmt.Errorf("not implemented: DomainID - domainId"))
}
func (r *announcementResolver) Domain(ctx context.Context, obj *models.Announcement) (*models.Domain, error) {
	panic(fmt.Errorf("not implemented: Domain - domain"))
}
func (r *announcementResolver) Level(ctx context.Context, obj *models.Announcement) (*uint, error) {
	panic(fmt.Errorf("not implemented: Level - level"))
}
func (r *Resolver) Announcement() generated.AnnouncementResolver { return &announcementResolver{r} }
type announcementResolver struct{ *Resolver }
*/
