package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"

	"github.com/hotbrainy/go-betting/backend/graph/model"
)

// CreateGameAPI is the resolver for the createGameApi field.
func (r *mutationResolver) CreateGameAPI(ctx context.Context, input model.NewGameAPIInput) (*model.GameAPI, error) {
	panic(fmt.Errorf("not implemented: CreateGameAPI - createGameApi"))
}

// UpdateGameAPI is the resolver for the updateGameApi field.
func (r *mutationResolver) UpdateGameAPI(ctx context.Context, id uint, input model.UpdateGameAPIInput) (*model.GameAPI, error) {
	panic(fmt.Errorf("not implemented: UpdateGameAPI - updateGameApi"))
}

// DeleteGameAPI is the resolver for the deleteGameApi field.
func (r *mutationResolver) DeleteGameAPI(ctx context.Context, id uint) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteGameAPI - deleteGameApi"))
}

// GetGameApis is the resolver for the getGameApis field.
func (r *queryResolver) GetGameApis(ctx context.Context, filters []*model.Filter, orders []*model.Order, pagination *model.Pagination) (*model.GameAPIList, error) {
	panic(fmt.Errorf("not implemented: GetGameApis - getGameApis"))
}
