package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"

	"github.com/hotbrainy/go-betting/backend/graph/model"
)

// CreateSetting is the resolver for the createSetting field.
func (r *mutationResolver) CreateSetting(ctx context.Context, input model.NewSettingInput) (*model.Setting, error) {
	panic(fmt.Errorf("not implemented: CreateSetting - createSetting"))
}

// UpdateSetting is the resolver for the updateSetting field.
func (r *mutationResolver) UpdateSetting(ctx context.Context, id uint, input model.UpdateSettingInput) (*model.Setting, error) {
	panic(fmt.Errorf("not implemented: UpdateSetting - updateSetting"))
}

// DeleteSetting is the resolver for the deleteSetting field.
func (r *mutationResolver) DeleteSetting(ctx context.Context, id uint) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteSetting - deleteSetting"))
}

// GetSetting is the resolver for the getSetting field.
func (r *queryResolver) GetSetting(ctx context.Context) (*model.Setting, error) {
	panic(fmt.Errorf("not implemented: GetSetting - getSetting"))
}
