// Helper script to generate page title mappings
// This is a reference file to help identify which titles to use for which pages

const pageTitleMap = {
  // Admin pages
  'admin/admin/admin': 'Admin - Admin Management Page',
  'admin/admin/log': 'Admin - Admin Log Page',
  'admin/admin/status': 'Admin - Admin Status Page',
  'admin/alert': 'Admin - Alerts Page',
  'admin/board/bulletin': 'Admin - Bulletin Page',
  'admin/board/comments': 'Admin - Comments Page',
  'admin/board/events': 'Admin - Events Page',
  'admin/board/notifications': 'Admin - Notifications Page',
  'admin/financals/general': 'Admin - Financial General Page',
  'admin/financals/integratedtransferhistory': 'Admin - Integrated Transfer History Page',
  'admin/financals/memberdwhistory': 'Admin - Member Deposit Withdrawal History Page',
  'admin/financals/membertransferhistory': 'Admin - Member Transfer History Page',
  'admin/financals/totaltransferhistory': 'Admin - Total Transfer History Page',
  'admin/game/api/hororlink': 'Admin - Hororlink API Page',
  'admin/game/api/khan': 'Admin - Khan API Page',
  'admin/game/api/redfox': 'Admin - Redfox API Page',
  'admin/game/api/revolution': 'Admin - Revolution API Page',
  'admin/game/api/slotcity': 'Admin - Slotcity API Page',
  'admin/game/api/swix': 'Admin - Swix API Page',
  'admin/game/api/wildgames': 'Admin - Wildgames API Page',
  'admin/game/bettingstatus/casinoLive': 'Admin - Casino Live Betting Status Page',
  'admin/game/bettingstatus/casinoSlot': 'Admin - Casino Slot Betting Status Page',
  'admin/game/bettingstatus/miniGame': 'Admin - Mini Game Betting Status Page',
  'admin/game/bettingstatus/sports': 'Admin - Sports Betting Status Page',
  'admin/game/casino/live': 'Admin - Casino Live Page',
  'admin/game/casino/poker': 'Admin - Casino Poker Page',
  'admin/game/casino/slot': 'Admin - Casino Slot Page',
  'admin/game/mini/bepick': 'Admin - Bepick Mini Game Page',
  'admin/game/mini/dhpowerball': 'Admin - DH Powerball Page',
  'admin/game/mini/eos': 'Admin - EOS Mini Game Page',
  'admin/game/mini/eos1min': 'Admin - EOS 1min Page',
  'admin/game/mini/eos2min': 'Admin - EOS 2min Page',
  'admin/game/mini/eos3min': 'Admin - EOS 3min Page',
  'admin/game/mini/eos4min': 'Admin - EOS 4min Page',
  'admin/game/mini/eos5min': 'Admin - EOS 5min Page',
  'admin/game/mini/pbg': 'Admin - PBG Mini Game Page',
  'admin/game/sports/basic': 'Admin - Sports Basic Page',
  'admin/game/sports/betting': 'Admin - Sports Betting Page',
  'admin/game/sports/countryOrder': 'Admin - Sports Country Order Page',
  'admin/game/sports/mainEvent': 'Admin - Sports Main Event Page',
  'admin/game/sports/market': 'Admin - Sports Market Page',
  'admin/game/sports/marketCombinedBetting': 'Admin - Sports Market Combined Betting Page',
  'admin/game/sports/matchEndsAuto': 'Admin - Sports Match Ends Auto Page',
  'admin/game/sports/matchEndsLive': 'Admin - Sports Match Ends Live Page',
  'admin/game/sports/matchEndsManual': 'Admin - Sports Match Ends Manual Page',
  'admin/game/sports/matchManagementAuto': 'Admin - Sports Match Management Auto Page',
  'admin/game/sports/matchManagementChangeHistory': 'Admin - Sports Match Management Change History Page',
  'admin/game/sports/matchManagementLive': 'Admin - Sports Match Management Live Page',
  'admin/game/sports/matchManagementManual': 'Admin - Sports Match Management Manual Page',
  'admin/game/sports': 'Admin - Sports Page',
  'admin/game/sports/recalibrationBetting': 'Admin - Sports Recalibration Betting Page',
  'admin/game/sports/recalibrationMarket': 'Admin - Sports Recalibration Market Page',
  'admin/game/sports/settings': 'Admin - Sports Settings Page',
  'admin/inbox/custom': 'Admin - Custom Inbox Page',
  'admin/inbox/group': 'Admin - Group Inbox Page',
  'admin/inbox/sample': 'Admin - Sample Inbox Page',
  'admin/partners/distributor': 'Admin - Distributor Page',
  'admin/partners/distributor/pages/losingSetting': 'Admin - Losing Setting Page',
  'admin/partners/distributor/pages/rollingCasino': 'Admin - Rolling Casino Page',
  'admin/partners/domain': 'Admin - Partners Domain Page',
  'admin/partners/status': 'Admin - Partners Status Page',
  'admin/popup/distributor-inquiry': 'Admin - Distributor Inquiry Page',
  'admin/popup/member-deposit': 'Admin - Member Deposit Page',
  'admin/popup/member-join': 'Admin - Member Join Page',
  'admin/popup/member-support': 'Admin - Member Support Page',
  'admin/popup/member-withdraw': 'Admin - Member Withdraw Page',
  'admin/popup/partner-deposit': 'Admin - Partner Deposit Page',
  'admin/popup/partner-withdraw': 'Admin - Partner Withdraw Page',
  'admin/popup/rolling-conversion': 'Admin - Rolling Conversion Page',
  'admin/popup/sports-bet-alert': 'Admin - Sports Bet Alert Page',
  'admin/popup/total-settlement': 'Admin - Total Settlement Page',
  'admin/popup/user': 'Admin - User Popup Page',
  'admin/settings/alarm': 'Admin - Alarm Settings Page',
  'admin/settings/bank': 'Admin - Bank Settings Page',
  'admin/settings/contact': 'Admin - Contact Settings Page',
  'admin/settings/design': 'Admin - Design Settings Page',
  'admin/settings/domain': 'Admin - Domain Settings Page',
  'admin/settings/global': 'Admin - Global Settings Page',
  'admin/settings/level': 'Admin - Level Settings Page',
  'admin/settings/menu': 'Admin - Menu Settings Page',
  'admin/settings/popup': 'Admin - Popup Settings Page',
  'admin/settings/site': 'Admin - Site Settings Page',
  'admin/settings/sms': 'Admin - SMS Settings Page',
  'admin/settlements/distributorstatistics': 'Admin - Distributor Statistics Page',
  'admin/settlements/distributorstatisticsdetail': 'Admin - Distributor Statistics Detail Page',
  'admin/settlements/fullcoupondetail': 'Admin - Full Coupon Detail Page',
  'admin/settlements/fullpointshistory': 'Admin - Full Points History Page',
  'admin/settlements/losingaccumulationhistory': 'Admin - Losing Accumulation History Page',
  'admin/settlements/losingdetail': 'Admin - Losing Detail Page',
  'admin/settlements/rollingaccumulationhistory': 'Admin - Rolling Accumulation History Page',
  'admin/settlements/rollingconversionhistory': 'Admin - Rolling Conversion History Page',
  'admin/support/center': 'Admin - Support Center Page',
  'admin/support/sample': 'Admin - Support Sample Page',
  'admin/support/tickets': 'Admin - Support Tickets Page',
  'admin/users/activity': 'Admin - User Activity Page',
  'admin/users/smslog': 'Admin - User SMS Log Page',
  
  // Partner pages
  'partner/game/bettingstatus/casino': 'Partner - Casino Betting Status Page',
  'partner/game/bettingstatus/miniGame': 'Partner - Mini Game Betting Status Page',
  'partner/game/bettingstatus/slot': 'Partner - Slot Betting Status Page',
  'partner/member-management/connectedMember': 'Partner - Connected Member Page',
  'partner/member-management/directMemberDepositWithdrawal': 'Partner - Direct Member Deposit Withdrawal Page',
  'partner/member-management/directMemberPointsDetails': 'Partner - Direct Member Points Details Page',
  'partner/member-management/entireMemberDepositWithdrawal': 'Partner - Entire Member Deposit Withdrawal Page',
  'partner/member-management/integratedMoneyTransferHistory': 'Partner - Integrated Money Transfer History Page',
  'partner/member-management/waitingForMemberApproval': 'Partner - Waiting For Member Approval Page',
  'partner/mySettlementManagement/moneyHistory': 'Partner - Money History Page',
  'partner/mySettlementManagement/myDepositWidthdrawal': 'Partner - My Deposit Withdrawal Page',
  'partner/mySettlementManagement/pointConversion': 'Partner - Point Conversion Page',
  'partner/mySettlementManagement/pointDetails': 'Partner - Point Details Page',
  'partner/mySettlementManagement/rollingHistory': 'Partner - Rolling History Page',
  'partner/mySettlementManagement/rollingTransaction': 'Partner - Rolling Transaction Page',
  'partner/mySettlementManagement/settlementDetails': 'Partner - Settlement Details Page',
  'partner/noteManagement/myNotes': 'Partner - My Notes Page',
  'partner/popup/distributor-inquiry': 'Partner - Distributor Inquiry Page',
  'partner/popup/member-deposit': 'Partner - Member Deposit Page',
  'partner/popup/member-join': 'Partner - Member Join Page',
  'partner/popup/member-support': 'Partner - Member Support Page',
  'partner/popup/member-withdraw': 'Partner - Member Withdraw Page',
  'partner/popup/partner-deposit': 'Partner - Partner Deposit Page',
  'partner/popup/partner-withdraw': 'Partner - Partner Withdraw Page',
  'partner/popup/rolling-conversion': 'Partner - Rolling Conversion Page',
  'partner/popup/sports-bet-alert': 'Partner - Sports Bet Alert Page',
  'partner/popup/total-settlement': 'Partner - Total Settlement Page',
  'partner/popup/user': 'Partner - User Popup Page',
  'partner/sub-management/sub-distributor': 'Partner - Sub Distributor Page',
  'partner/sub-management/sub-member-list': 'Partner - Sub Member List Page',
  'partner/support/center': 'Partner - Support Center Page',
  
  // Main pages
  'bulletin': 'TOTOCLUB - Bulletin Page',
  'users': 'TOTOCLUB - Users Page',
  'users/upload': 'TOTOCLUB - User Upload Page',
  
  // Mini game pages
  'bepick': 'TOTOCLUB - Bepick Page',
  'dhpowerball': 'TOTOCLUB - DH Powerball Page',
  'eos': 'TOTOCLUB - EOS Page',
  'eos1': 'TOTOCLUB - EOS 1min Page',
  'eos2': 'TOTOCLUB - EOS 2min Page',
  'eos3': 'TOTOCLUB - EOS 3min Page',
  'eos4': 'TOTOCLUB - EOS 4min Page',
  'eos5': 'TOTOCLUB - EOS 5min Page',
  'pbg': 'TOTOCLUB - PBG Page',
};

module.exports = { pageTitleMap };

