import React from "react";
import type { Metadata } from "next";
import PartnerRootLayout from "@/components/Partner/Layout";
import "@/styles/globals.css";
import 'quill/dist/quill.snow.css';
import DeviceTracker from "@/components/Common/DeviceTracker";
import PartnerContent from "@/app/(partner)/PartnerContent";

export const metadata: Metadata = {
  title: "Partner",
  description: "Generated by Betting",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PartnerRootLayout>
      <DeviceTracker />
      <PartnerContent>
        {children}
      </PartnerContent>
    </PartnerRootLayout>
  );
}