import type { Metadata } from "next";

import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

import localFont from "next/font/local";
import "@/styles/globals.css";
import { ConfigProvider } from "antd";
import JotaiContextProvider from "@/contexts/JotaiContextProvider";

const geistSans = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Betting",
  description: "Generated by Betting",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale} className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <JotaiContextProvider>
          <NextIntlClientProvider locale={locale}>
            <ConfigProvider locale={{ locale }}>
              {children}
            </ConfigProvider>
          </NextIntlClientProvider>
        </JotaiContextProvider>
      </body>
    </html>
  );
}
