import type { Metadata } from "next";

import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

import { AntdRegistry } from "@ant-design/nextjs-registry";

import localFont from "next/font/local";
import "@/styles/icomoon.css";
import "@/styles/globals.css";
import "@ant-design/v5-patch-for-react-19";
import { ConfigProvider } from "antd";
import JotaiContextProvider from "@/contexts/JotaiContextProvider";
// import { AuthProvider } from "@/context/AuthContext";

import zhCN from "antd/locale/zh_CN";
import enUS from "antd/locale/en_US";
import thTH from "antd/locale/th_TH";
import koTH from "antd/locale/ko_KR";

const geistSans = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Betting",
  description: "Generated by Betting",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const locales: any = {
    cn: zhCN,
    en: enUS,
    th: thTH,
    ko: koTH,
  };
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // style={{
        //   overflow: "hidden",
        // }}
      >
        <AntdRegistry>
          <JotaiContextProvider>
            <NextIntlClientProvider locale={locale}>
              <ConfigProvider locale={locales[locale]}>
                {children}
              </ConfigProvider>
            </NextIntlClientProvider>
          </JotaiContextProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
