import type { Metadata } from "next";
import "@/styles/globals.css";
import AdminRootLayout from "@/components/AdminLayout";

export const metadata: Metadata = {
  title: "Betting",
  description: "Generated by Betting",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AdminRootLayout>{children}</AdminRootLayout>;
}
